name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Quando fai un push al ramo main, esegui il deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build site
        run: npm run build  # Se hai un processo di build (altrimenti questo passo non serve)

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Esegui il deploy sul ramo gh-pages
          folder: build     # Qui metti la cartella che contiene i file statici del sito
